language: generic
dist: trusty
sudo: required
os: linux
group: edge
addons:
  apt:
    packages:
      - tcl
      - tcllib
before_install:
  - lsb_release -a
  - uname -a
  - echo 'puts $tcl_version' |tclsh
before_script:
  - chmod +x test/run.tcl
script: ./test/run.tcl
